apiVersion: v1
kind: ReplicationController
metadata:
  name: go-api
  namespace: default
spec:
  replicas: 10
  selector:
    app: go-api
  template:
    metadata:
      name: go-api
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api-container
          image: rpi-master:5000/go-api:v1
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: go-api
  namespace: default
spec:
  selector:
    app: go-api
  ports:
    - port: 9001
      targetPort: 80
  type: LoadBalancer
