apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-registry-pv
  namespace: kube-system
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs/registry
    server: 192.168.3.10
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: kube-registry-pvc
    namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-registry-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
